### ISSUE TITLE
Missing deriveKeyFor() before prepareNextInterval()?

### ISSUE THREAD

**Issue by dschuermann** [imichaelmiers/libforwardsec#2]
In your example the following code is used to start interval 2, and then interval 31:

```
    // When this interval is over we can derive the next interval 
    forwardSecureEncryption.prepareNextInterval(pk,sk);
    // if at some point you need to derive some interval in the future
    // e.g. your intervals are one second long , but for 30 seconds you got no traffic,
    // then use 

    forwardSecureEncryption.deriveKeyFor(pk,sk,31);
    // note, to puncture this interval , you will then need to actually prepare it's child keys too
    // if you don't do so, you cannot decrypt. To do so, use:
    forwardSecureEncryption.prepareIntervalAfter(pk,sk,31);
```

Maybe I am misunderstanding something, but isn't it required to also do `deriveKeyFor(pk,sk,2)` before `prepareNextInterval(pk,sk);` ?

**Comment by imichaelmiers** [comment]
I don't believe so.  
I believe the following is the case, let me know if you see anything to the contrary. There is a tree of keys.   Child keys need to be derived before we can puncture parent keys

. PrepareNextInterval  derives child keys  for the current interval (we map nodes in the tree to intervals by an in order traversal), given the parent. When we instantiate the scheme, we get the root of the tree (actually, we derive its left and right children too but that's just the way I wrote it). So PrepareNextInterval can run.

deriveKeyFor  doesn't derive child keys, it just walks down the tree deriving keys until you get the key you asked for. 

prepareIntervalAfter takes an arbitrary node in the tree and derives its children.  But it requires that the parent already be derived somehow. Which is why you need to run deriveKeyFor.

Looking back on it, I am not sure the API choices were the cleanest.  Let me know if you have any other questions. I can be reached at my github username at gmail.com or the email address in the paper.

**Comment by dschuermann** [comment]
@imichaelmiers Thanks for your help and explanation :)
